INFO 2024-04-10 00:23:25,191 autoreload 14716 10932 Watching for file changes with StatReloader
WARNING 2024-04-10 00:23:30,981 log 14716 5400 Not Found: /
WARNING 2024-04-10 00:23:30,982 basehttp 14716 5400 "GET / HTTP/1.1" 404 2166
WARNING 2024-04-10 00:23:31,953 log 14716 5400 Not Found: /favicon.ico
WARNING 2024-04-10 00:23:31,953 basehttp 14716 5400 "GET /favicon.ico HTTP/1.1" 404 2217
INFO 2024-04-10 00:23:54,906 basehttp 14716 16828 "GET /shop/fake_db/ HTTP/1.1" 200 63
ERROR 2024-04-10 00:24:02,600 log 14716 16828 Internal Server Error: /shop/coi/
Traceback (most recent call last):
  File "E:\GeekBrains\Учеба GeekBrains\3 quarter. Final\2. Django framework (Seminars)\GB_Django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "E:\GeekBrains\Учеба GeekBrains\3 quarter. Final\2. Django framework (Seminars)\GB_Django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\GeekBrains\Учеба GeekBrains\3 quarter. Final\2. Django framework (Seminars)\GB_Django\Seminar3\HomeWork\shopapp\views.py", line 90, in customer_ordered_items
    ordered_items_last_year = get_ordered_items_within_period(customer, 365)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\GeekBrains\Учеба GeekBrains\3 quarter. Final\2. Django framework (Seminars)\GB_Django\Seminar3\HomeWork\shopapp\views.py", line 104, in get_ordered_items_within_period
    ordered_items.update(order.items.all())
                         ^^^^^^^^^^^
AttributeError: 'Order' object has no attribute 'items'
ERROR 2024-04-10 00:24:02,603 basehttp 14716 16828 "GET /shop/coi/ HTTP/1.1" 500 73825
INFO 2024-04-10 00:26:42,701 basehttp 14716 1672 "GET /shop/fake_db/ HTTP/1.1" 200 63
ERROR 2024-04-10 00:26:56,053 log 14716 1672 Internal Server Error: /shop/coi/
Traceback (most recent call last):
  File "E:\GeekBrains\Учеба GeekBrains\3 quarter. Final\2. Django framework (Seminars)\GB_Django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "E:\GeekBrains\Учеба GeekBrains\3 quarter. Final\2. Django framework (Seminars)\GB_Django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\GeekBrains\Учеба GeekBrains\3 quarter. Final\2. Django framework (Seminars)\GB_Django\Seminar3\HomeWork\shopapp\views.py", line 90, in customer_ordered_items
    ordered_items_last_year = get_ordered_items_within_period(customer, 365)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\GeekBrains\Учеба GeekBrains\3 quarter. Final\2. Django framework (Seminars)\GB_Django\Seminar3\HomeWork\shopapp\views.py", line 104, in get_ordered_items_within_period
    ordered_items.update(order.items.all())
                         ^^^^^^^^^^^
AttributeError: 'Order' object has no attribute 'items'
ERROR 2024-04-10 00:26:56,054 basehttp 14716 1672 "GET /shop/coi/ HTTP/1.1" 500 74305
INFO 2024-04-10 00:42:34,299 autoreload 14716 10932 E:\GeekBrains\Учеба GeekBrains\3 quarter. Final\2. Django framework (Seminars)\GB_Django\Seminar3\HomeWork\shopapp\views.py changed, reloading.
INFO 2024-04-10 00:42:35,095 autoreload 5252 9176 Watching for file changes with StatReloader
INFO 2024-04-10 00:43:05,715 autoreload 5252 9176 E:\GeekBrains\Учеба GeekBrains\3 quarter. Final\2. Django framework (Seminars)\GB_Django\Seminar3\HomeWork\shopapp\models.py changed, reloading.
INFO 2024-04-10 00:43:06,369 autoreload 6056 6348 Watching for file changes with StatReloader
INFO 2024-04-10 00:43:20,133 autoreload 6056 6348 E:\GeekBrains\Учеба GeekBrains\3 quarter. Final\2. Django framework (Seminars)\GB_Django\Seminar3\HomeWork\shopapp\models.py changed, reloading.
INFO 2024-04-10 00:43:20,830 autoreload 17176 16884 Watching for file changes with StatReloader
INFO 2024-04-10 00:44:09,199 autoreload 17176 16884 E:\GeekBrains\Учеба GeekBrains\3 quarter. Final\2. Django framework (Seminars)\GB_Django\Seminar3\HomeWork\shopapp\models.py changed, reloading.
INFO 2024-04-10 00:44:09,916 autoreload 17136 16044 Watching for file changes with StatReloader
ERROR 2024-04-10 00:44:10,954 log 17136 1720 Internal Server Error: /shop/coi/
Traceback (most recent call last):
  File "E:\GeekBrains\Учеба GeekBrains\3 quarter. Final\2. Django framework (Seminars)\GB_Django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "E:\GeekBrains\Учеба GeekBrains\3 quarter. Final\2. Django framework (Seminars)\GB_Django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\GeekBrains\Учеба GeekBrains\3 quarter. Final\2. Django framework (Seminars)\GB_Django\Seminar3\HomeWork\shopapp\views.py", line 91, in customer_ordered_items
    customer.ordered_items_last_week = ordered_items_last_week
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\GeekBrains\Учеба GeekBrains\3 quarter. Final\2. Django framework (Seminars)\GB_Django\.venv\Lib\site-packages\django\db\models\fields\related_descriptors.py", line 659, in __set__
    raise TypeError(
TypeError: Direct assignment to the forward side of a many-to-many set is prohibited. Use ordered_items_last_week.set() instead.
ERROR 2024-04-10 00:44:10,956 basehttp 17136 1720 "GET /shop/coi/ HTTP/1.1" 500 74290
INFO 2024-04-10 00:49:56,731 autoreload 17136 16044 E:\GeekBrains\Учеба GeekBrains\3 quarter. Final\2. Django framework (Seminars)\GB_Django\Seminar3\HomeWork\shopapp\views.py changed, reloading.
INFO 2024-04-10 00:49:57,377 autoreload 16704 6280 Watching for file changes with StatReloader
ERROR 2024-04-10 00:50:00,805 log 16704 4940 Internal Server Error: /shop/coi/
Traceback (most recent call last):
  File "E:\GeekBrains\Учеба GeekBrains\3 quarter. Final\2. Django framework (Seminars)\GB_Django\.venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\GeekBrains\Учеба GeekBrains\3 quarter. Final\2. Django framework (Seminars)\GB_Django\.venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 329, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such table: shopapp_customer_ordered_items_last_week

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\GeekBrains\Учеба GeekBrains\3 quarter. Final\2. Django framework (Seminars)\GB_Django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "E:\GeekBrains\Учеба GeekBrains\3 quarter. Final\2. Django framework (Seminars)\GB_Django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\GeekBrains\Учеба GeekBrains\3 quarter. Final\2. Django framework (Seminars)\GB_Django\Seminar3\HomeWork\shopapp\views.py", line 92, in customer_ordered_items
    customer.ordered_items_last_week.set(ordered_items_last_week)
  File "E:\GeekBrains\Учеба GeekBrains\3 quarter. Final\2. Django framework (Seminars)\GB_Django\.venv\Lib\site-packages\django\db\models\fields\related_descriptors.py", line 1281, in set
    old_ids = set(
              ^^^^
  File "E:\GeekBrains\Учеба GeekBrains\3 quarter. Final\2. Django framework (Seminars)\GB_Django\.venv\Lib\site-packages\django\db\models\query.py", line 400, in __iter__
    self._fetch_all()
  File "E:\GeekBrains\Учеба GeekBrains\3 quarter. Final\2. Django framework (Seminars)\GB_Django\.venv\Lib\site-packages\django\db\models\query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\GeekBrains\Учеба GeekBrains\3 quarter. Final\2. Django framework (Seminars)\GB_Django\.venv\Lib\site-packages\django\db\models\query.py", line 287, in __iter__
    for row in compiler.results_iter(
               ^^^^^^^^^^^^^^^^^^^^^^
  File "E:\GeekBrains\Учеба GeekBrains\3 quarter. Final\2. Django framework (Seminars)\GB_Django\.venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1513, in results_iter
    results = self.execute_sql(
              ^^^^^^^^^^^^^^^^^
  File "E:\GeekBrains\Учеба GeekBrains\3 quarter. Final\2. Django framework (Seminars)\GB_Django\.venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "E:\GeekBrains\Учеба GeekBrains\3 quarter. Final\2. Django framework (Seminars)\GB_Django\.venv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\GeekBrains\Учеба GeekBrains\3 quarter. Final\2. Django framework (Seminars)\GB_Django\.venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\GeekBrains\Учеба GeekBrains\3 quarter. Final\2. Django framework (Seminars)\GB_Django\.venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\GeekBrains\Учеба GeekBrains\3 quarter. Final\2. Django framework (Seminars)\GB_Django\.venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "E:\GeekBrains\Учеба GeekBrains\3 quarter. Final\2. Django framework (Seminars)\GB_Django\.venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "E:\GeekBrains\Учеба GeekBrains\3 quarter. Final\2. Django framework (Seminars)\GB_Django\.venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\GeekBrains\Учеба GeekBrains\3 quarter. Final\2. Django framework (Seminars)\GB_Django\.venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 329, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such table: shopapp_customer_ordered_items_last_week
ERROR 2024-04-10 00:50:00,810 basehttp 16704 4940 "GET /shop/coi/ HTTP/1.1" 500 143067
INFO 2024-04-10 00:50:41,795 autoreload 9000 8532 Watching for file changes with StatReloader
ERROR 2024-04-10 00:50:43,699 log 9000 16280 Internal Server Error: /shop/coi/
Traceback (most recent call last):
  File "E:\GeekBrains\Учеба GeekBrains\3 quarter. Final\2. Django framework (Seminars)\GB_Django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "E:\GeekBrains\Учеба GeekBrains\3 quarter. Final\2. Django framework (Seminars)\GB_Django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\GeekBrains\Учеба GeekBrains\3 quarter. Final\2. Django framework (Seminars)\GB_Django\Seminar3\HomeWork\shopapp\views.py", line 96, in customer_ordered_items
    return render(request, 'ordered_items.html', {'customers': customers})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\GeekBrains\Учеба GeekBrains\3 quarter. Final\2. Django framework (Seminars)\GB_Django\.venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\GeekBrains\Учеба GeekBrains\3 quarter. Final\2. Django framework (Seminars)\GB_Django\.venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\GeekBrains\Учеба GeekBrains\3 quarter. Final\2. Django framework (Seminars)\GB_Django\.venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: ordered_items.html
ERROR 2024-04-10 00:50:43,702 basehttp 9000 16280 "GET /shop/coi/ HTTP/1.1" 500 83455
INFO 2024-04-10 00:52:00,662 autoreload 9000 8532 E:\GeekBrains\Учеба GeekBrains\3 quarter. Final\2. Django framework (Seminars)\GB_Django\Seminar3\HomeWork\shopapp\views.py changed, reloading.
INFO 2024-04-10 00:52:01,336 autoreload 17032 16916 Watching for file changes with StatReloader
INFO 2024-04-10 00:54:03,718 autoreload 17032 16916 E:\GeekBrains\Учеба GeekBrains\3 quarter. Final\2. Django framework (Seminars)\GB_Django\Seminar3\HomeWork\shopapp\views.py changed, reloading.
INFO 2024-04-10 00:54:04,431 autoreload 12784 11588 Watching for file changes with StatReloader
ERROR 2024-04-10 00:54:05,079 log 12784 11548 Internal Server Error: /shop/coi/
Traceback (most recent call last):
  File "E:\GeekBrains\Учеба GeekBrains\3 quarter. Final\2. Django framework (Seminars)\GB_Django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "E:\GeekBrains\Учеба GeekBrains\3 quarter. Final\2. Django framework (Seminars)\GB_Django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\GeekBrains\Учеба GeekBrains\3 quarter. Final\2. Django framework (Seminars)\GB_Django\Seminar3\HomeWork\shopapp\views.py", line 93, in customer_ordered_items
    return render(request, 'shopapp/ordered_items.html', {'customers': customers})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\GeekBrains\Учеба GeekBrains\3 quarter. Final\2. Django framework (Seminars)\GB_Django\.venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\GeekBrains\Учеба GeekBrains\3 quarter. Final\2. Django framework (Seminars)\GB_Django\.venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\GeekBrains\Учеба GeekBrains\3 quarter. Final\2. Django framework (Seminars)\GB_Django\.venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: shopapp/ordered_items.html
ERROR 2024-04-10 00:54:05,081 basehttp 12784 11548 "GET /shop/coi/ HTTP/1.1" 500 83583
INFO 2024-04-10 00:59:02,163 autoreload 12784 11588 E:\GeekBrains\Учеба GeekBrains\3 quarter. Final\2. Django framework (Seminars)\GB_Django\Seminar3\HomeWork\HomeWork\settings.py changed, reloading.
INFO 2024-04-10 00:59:02,802 autoreload 16712 11136 Watching for file changes with StatReloader
INFO 2024-04-10 01:03:26,149 autoreload 16712 11136 E:\GeekBrains\Учеба GeekBrains\3 quarter. Final\2. Django framework (Seminars)\GB_Django\Seminar3\HomeWork\shopapp\views.py changed, reloading.
INFO 2024-04-10 01:03:26,834 autoreload 16496 7336 Watching for file changes with StatReloader
INFO 2024-04-10 01:05:29,623 autoreload 16496 7336 E:\GeekBrains\Учеба GeekBrains\3 quarter. Final\2. Django framework (Seminars)\GB_Django\Seminar3\HomeWork\shopapp\views.py changed, reloading.
INFO 2024-04-10 01:05:30,272 autoreload 17284 5568 Watching for file changes with StatReloader
ERROR 2024-04-10 01:05:33,322 log 17284 10180 Internal Server Error: /shop/coi/
Traceback (most recent call last):
  File "E:\GeekBrains\Учеба GeekBrains\3 quarter. Final\2. Django framework (Seminars)\GB_Django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "E:\GeekBrains\Учеба GeekBrains\3 quarter. Final\2. Django framework (Seminars)\GB_Django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\GeekBrains\Учеба GeekBrains\3 quarter. Final\2. Django framework (Seminars)\GB_Django\Seminar3\HomeWork\shopapp\views.py", line 49, in customer_ordered_items
    return render(request, 'shopapp/ordered_items.html', {'customers': customers})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\GeekBrains\Учеба GeekBrains\3 quarter. Final\2. Django framework (Seminars)\GB_Django\.venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\GeekBrains\Учеба GeekBrains\3 quarter. Final\2. Django framework (Seminars)\GB_Django\.venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\GeekBrains\Учеба GeekBrains\3 quarter. Final\2. Django framework (Seminars)\GB_Django\.venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: shopapp/ordered_items.html
ERROR 2024-04-10 01:05:33,325 basehttp 17284 10180 "GET /shop/coi/ HTTP/1.1" 500 83682
INFO 2024-04-10 01:06:25,043 autoreload 17080 8144 Watching for file changes with StatReloader
ERROR 2024-04-10 01:06:28,574 log 17080 16620 Internal Server Error: /shop/coi/
Traceback (most recent call last):
  File "E:\GeekBrains\Учеба GeekBrains\3 quarter. Final\2. Django framework (Seminars)\GB_Django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "E:\GeekBrains\Учеба GeekBrains\3 quarter. Final\2. Django framework (Seminars)\GB_Django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\GeekBrains\Учеба GeekBrains\3 quarter. Final\2. Django framework (Seminars)\GB_Django\Seminar3\HomeWork\shopapp\views.py", line 49, in customer_ordered_items
    return render(request, 'shopapp/ordered_items.html', {'customers': customers})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\GeekBrains\Учеба GeekBrains\3 quarter. Final\2. Django framework (Seminars)\GB_Django\.venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\GeekBrains\Учеба GeekBrains\3 quarter. Final\2. Django framework (Seminars)\GB_Django\.venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\GeekBrains\Учеба GeekBrains\3 quarter. Final\2. Django framework (Seminars)\GB_Django\.venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: shopapp/ordered_items.html
ERROR 2024-04-10 01:06:28,576 basehttp 17080 16620 "GET /shop/coi/ HTTP/1.1" 500 83682
INFO 2024-04-10 01:09:08,589 autoreload 17080 8144 E:\GeekBrains\Учеба GeekBrains\3 quarter. Final\2. Django framework (Seminars)\GB_Django\Seminar3\HomeWork\HomeWork\settings.py changed, reloading.
INFO 2024-04-10 01:09:09,279 autoreload 17088 6808 Watching for file changes with StatReloader
ERROR 2024-04-10 01:09:14,860 log 17088 4728 Internal Server Error: /shop/coi/
Traceback (most recent call last):
  File "E:\GeekBrains\Учеба GeekBrains\3 quarter. Final\2. Django framework (Seminars)\GB_Django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "E:\GeekBrains\Учеба GeekBrains\3 quarter. Final\2. Django framework (Seminars)\GB_Django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\GeekBrains\Учеба GeekBrains\3 quarter. Final\2. Django framework (Seminars)\GB_Django\Seminar3\HomeWork\shopapp\views.py", line 49, in customer_ordered_items
    return render(request, 'shopapp/ordered_items.html', {'customers': customers})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\GeekBrains\Учеба GeekBrains\3 quarter. Final\2. Django framework (Seminars)\GB_Django\.venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\GeekBrains\Учеба GeekBrains\3 quarter. Final\2. Django framework (Seminars)\GB_Django\.venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\GeekBrains\Учеба GeekBrains\3 quarter. Final\2. Django framework (Seminars)\GB_Django\.venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: shopapp/ordered_items.html
ERROR 2024-04-10 01:09:14,862 basehttp 17088 4728 "GET /shop/coi/ HTTP/1.1" 500 84352
INFO 2024-04-10 01:10:32,573 autoreload 17088 6808 E:\GeekBrains\Учеба GeekBrains\3 quarter. Final\2. Django framework (Seminars)\GB_Django\Seminar3\HomeWork\HomeWork\settings.py changed, reloading.
INFO 2024-04-10 01:10:33,210 autoreload 5400 6728 Watching for file changes with StatReloader
INFO 2024-04-10 01:10:35,190 basehttp 5400 15648 "GET /shop/coi/ HTTP/1.1" 200 1
INFO 2024-04-10 01:46:08,711 autoreload 5400 6728 E:\GeekBrains\Учеба GeekBrains\3 quarter. Final\2. Django framework (Seminars)\GB_Django\Seminar3\HomeWork\shopapp\urls.py changed, reloading.
INFO 2024-04-10 01:46:09,440 autoreload 1272 8220 Watching for file changes with StatReloader
INFO 2024-04-10 01:46:32,840 autoreload 1272 8220 E:\GeekBrains\Учеба GeekBrains\3 quarter. Final\2. Django framework (Seminars)\GB_Django\Seminar3\HomeWork\shopapp\views.py changed, reloading.
INFO 2024-04-10 01:46:33,471 autoreload 16548 2684 Watching for file changes with StatReloader
INFO 2024-04-10 01:46:43,373 basehttp 16548 8840 "GET /shop/coi/7 HTTP/1.1" 200 1
INFO 2024-04-10 01:52:20,087 autoreload 16548 2684 E:\GeekBrains\Учеба GeekBrains\3 quarter. Final\2. Django framework (Seminars)\GB_Django\Seminar3\HomeWork\shopapp\urls.py changed, reloading.
INFO 2024-04-10 01:52:20,866 autoreload 15600 9112 Watching for file changes with StatReloader
INFO 2024-04-10 01:52:20,969 basehttp 15600 17044 "GET /shop/coi/7 HTTP/1.1" 200 166
INFO 2024-04-10 01:54:52,911 basehttp 15600 17044 "GET /shop/coi/7 HTTP/1.1" 200 163
INFO 2024-04-10 01:56:44,759 autoreload 15600 9112 E:\GeekBrains\Учеба GeekBrains\3 quarter. Final\2. Django framework (Seminars)\GB_Django\Seminar3\HomeWork\shopapp\urls.py changed, reloading.
INFO 2024-04-10 01:56:45,408 autoreload 8952 4804 Watching for file changes with StatReloader
INFO 2024-04-10 01:56:47,180 basehttp 8952 15312 "GET /shop/ordered_items/7 HTTP/1.1" 200 167
INFO 2024-04-10 01:57:57,454 basehttp 8952 15312 "GET /shop/ordered_items/7 HTTP/1.1" 200 167
INFO 2024-04-10 01:57:59,433 basehttp 8952 15312 "GET /shop/ordered_items/7 HTTP/1.1" 200 130
INFO 2024-04-10 01:58:20,927 basehttp 8952 15312 "GET /shop/ HTTP/1.1" 200 1637
INFO 2024-04-10 01:58:33,829 basehttp 8952 15312 "GET /shop/fake_db HTTP/1.1" 301 0
INFO 2024-04-10 01:58:34,749 basehttp 8952 11840 "GET /shop/fake_db/ HTTP/1.1" 200 63
INFO 2024-04-10 01:58:54,227 basehttp 8952 11840 "GET /shop/ordered_items/30 HTTP/1.1" 200 130
INFO 2024-04-10 02:03:50,554 basehttp 8952 11840 "GET /shop/ordered_items/30 HTTP/1.1" 200 2048
INFO 2024-04-10 02:04:01,224 basehttp 8952 11840 "GET /shop/ordered_items/7 HTTP/1.1" 200 1968
INFO 2024-04-10 02:05:43,175 basehttp 8952 11840 "GET /shop/ordered_items/7 HTTP/1.1" 200 2342
